### ISSUE TITLE
Numpad keys do not work in Chrome v49

### ISSUE THREAD

**Issue by edrachev** [PolymerElements/iron-a11y-keys#23] opened 2016-03-18 13:38 UTC
I have next configuration:

`<iron-a11y-keys keys="1 2 3"></iron-a11y-keys>`
`<script>`
`var keys = document.querySelector("iron-a11y-keys")`
`keys.target = document.body`
`keys.addEventListener("keys-pressed", function() {`
`alert("Pressed")`
`})`
`</script>`

I see alerts when I click numbers at the row and do not see it when I click numbers at the numpad.
In firefox and edge it works.

Working example:
https://jsfiddle.net/TrueEugene/jps1j3dc/

**Comment by valdrinkoshi** [comment] 2016-03-23 17:12
Hi @edrachev, looks like this is a duplicate of https://github.com/PolymerElements/iron-a11y-keys-behavior/issues/30, currently being fixed in https://github.com/PolymerElements/iron-a11y-keys-behavior/pull/35

Here the jsbin with the fix http://jsbin.com/kuseto/1/edit?html,output
Closing this, LMK if you meant a different issue & I'll reopen this again :)

**Closed as completed by valdrinkoshi** 2016-03-23 17:12 UTC
